title: "Math 254: Statistical Modeling and Applications"
description: "" 
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme


url: "https://eetripp.github.io"
baseurl: "/math254-notes/"

custom_css: true 

search_enabled: true

aux_links:
  "← Erin Tripp' Site":
    - "https://eetripp.github.io"

math: mathjax
